name: "[dispatch] daily build all core services"
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch를 입력해주세요(master와 release-x.y.z만 허용)'
        required: true
        default: 'master'
      version:
        description: 'version을 입력해주세요(x.y.z)'
        required: true
        default: '1.0.0'

env:
  BRANCH: ${{ github.event.inputs.branch }}
  VERSION: ${{ github.event.inputs.version }}
  SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}

jobs:
  core_console:
    if: github.repository_owner == 'GJ-playgroud'
    runs-on: ubuntu-latest
    steps:
      - name: task
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repo: GJ-playgroud/core-console
          workflow: dispatch_daily_build.yaml
          inputs: '{"branch": "${{ env.BRANCH }}", "version": "${{ env.VERSION }}"}'

  core_console_api:
    needs: core_console
    runs-on: ubuntu-latest
    steps:
      - name: task
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repo: GJ-playgroud/core-console-api
          workflow: dispatch_daily_build.yaml
          inputs: '{"branch": "${{ env.BRANCH }}", "version": "${{ env.VERSION }}"}'

  core_python_service:
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        target: ['core-python-service']
    needs: core_console_api
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: task
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repo: GJ-playgroud/${{ matrix.target }}
          workflow: dispatch_daily_build.yaml
          inputs: '{"branch": "${{ env.BRANCH }}", "version": "${{ env.VERSION }}"}'

  tools:
    strategy:
      fail-fast: false
      matrix:
        target: ['tools-spacectl', 'tools-image-cleaner']
    needs: core_python_service
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: task
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repo: GJ-playgroud/${{ matrix.target }}
          workflow: dispatch_daily_build.yaml
          inputs: '{"branch": "${{ env.BRANCH }}", "version": "${{ env.VERSION }}"}'

  doc:
    strategy:
      fail-fast: false
      matrix:
        target: ['doc-api-doc', 'doc-docs', 'doc-marketplace-assets']
    needs: tools
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: task
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repo: GJ-playgroud/${{ matrix.target }}
          workflow: dispatch_daily_build.yaml
          inputs: '{"branch": "${{ env.BRANCH }}", "version": "${{ env.VERSION }}"}'

  notify_to_slack:
    needs: [doc]
    runs-on: ubuntu-latest
    steps:
      - name: Slack
        if: always()
        uses: 8398a7/action-slack@v3.15.0
        with:
          status: ${{job.status}}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          author_name: Github Action Slack
